# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fabulous Time
email: digitalhistory@fas.harvard.edu
description: >
  Easily build rich timelines with hundreds of entries
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jaguillette
# show_downloads: true

# GitHub stuff
github:
  repository_url: https://github.com/jaguillette/fabulousTime
  repository_name: fabulousTime
  owner_url: https://github.com/jaguillette
  owner_name: Jeremy Guillette
  zip_url: https://github.com/jaguillette/fabulousTime/archive/master.zip
  tar_url: https://github.com/jaguillette/fabulousTime/archive/master.tar.gz
  is_project_page: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
